site_name: Documentation
site_description: Documentation for miyagi, a node based component development tool for JavaScript templating engines.

docs_dir: docs

extra_css:
  - extra.css

repo_name: mgrsskls/miyagi
repo_url: https://github.com/mgrsskls/miyagi
edit_uri: ""

theme:
  name: material
  font: false
  favicon: img/favicon.svg
  logo: img/logo.svg

plugins:
  - search # necessary for search to work
  - minify:
      minify_html: true

markdown_extensions:
  - codehilite:
      guess_lang: false

nav:
  - Home: index.md
  - Installation: installation.md
  - CLI commands:
      - Starting miyagi: cli-commands/start.md
      - Creating a component: cli-commands/components.md
      - Creating mock data: cli-commands/mocks.md
      - Creating a build: cli-commands/build.md
  - Configuration:
      - Available options: configuration/options.md
      - Via config file: configuration/config-file.md
      - Via CLI: configuration/cli.md
      - Extending template engine: configuration/extending-template-engine.md
  - Organizing your components: organizing-components.md
  - Automated styleguide: automated-styleguide.md
  - Component files:
      - Assets: component-files/assets.md
      - Documentation: component-files/documentation.md
      - Info: component-files/info.md
      - Mocks: component-files/mocks.md
      - Schema: component-files/schema.md
      - Template: component-files/template.md
  - Documentation: documentation.md
  - The web UI:
      - Overview: web-ui/overview.md
      - Component: web-ui/component.md
      - Variation: web-ui/variation.md
  - Supported template engines: template-engines.md
